#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/miaujuda_db;
#    username: postgres
#    password: postgres
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: update
#      properties:
#        hibernate:
#          show-sql: true 
#  sql:
#    init:
#      mode: always 
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-csr7e7hu0jms73cjh3t0-a.virginia-postgres.render.com:5432/miaujuda
    username: miaujuda_user
    password: h2IDVpGF0GjYwHu8fzTs13gWeLbh3PCC
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show-sql: true 
  sql:
    init:
      mode: always

