spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-csr7e7hu0jms73cjh3t0-a.virginia-postgres.render.com:5432/miaujuda
    username: miaujuda_user
    password: h2IDVpGF0GjYwHu8fzTs13gWeLbh3PCC
  jpa:
    hibernate:
      ddl-auto: update
