spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/miaujuda 
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
