name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_DB: miaujuda
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checar código
        uses: actions/checkout@v2

      - name: Configurar JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Instalar Maven
        run: sudo apt-get install maven

      - name: Esperar PostgreSQL ficar disponível
        run: |
          while ! pg_isready -h localhost -p 5432 -U postgres; do
            echo "Aguardando PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL está pronto!"

      - name: Construir e testar backend
        run: |
          cd backend
          mvn clean install

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Construir e testar frontend
        run: |
          cd frontend
          npm install
          npm run build --prod
